USE school_profile;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS logs;
DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS social_media;
DROP TABLE IF EXISTS ppdb;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS banners;
DROP TABLE IF EXISTS sliders;
DROP TABLE IF EXISTS testimonials;
DROP TABLE IF EXISTS faqs;
DROP TABLE IF EXISTS downloads;
DROP TABLE IF EXISTS videos;
DROP TABLE IF EXISTS gallery_images;
DROP TABLE IF EXISTS galleries;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS announcements;
DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS news_categories;
DROP TABLE IF EXISTS programs;
DROP TABLE IF EXISTS facilities;
DROP TABLE IF EXISTS achievements;
DROP TABLE IF EXISTS student_statistics;
DROP TABLE IF EXISTS staffs;
DROP TABLE IF EXISTS teachers;
DROP TABLE IF EXISTS school_profiles;
DROP TABLE IF EXISTS menus;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

SET FOREIGN_KEY_CHECKS = 1;
